config/routes.rb
Rails.application.routes.draw do
    resources :books
    root 'books#index'
    get '/delete/:id' => 'books#destroy', as: :delete
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    get '/signup'=> 'users#new'
    post '/users' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
      helper_method :current_user

      def authorize
        redirect_to '/login' unless current_user
      end

      def check_owner
        book = Book.find(params[:id])
        redirect_to '/' unless book.user_id == current_user.id
      end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(bookparams)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(bookparams)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy!
    redirect_to books_path
  end

  private

  def bookparams
    params.require(:book).permit(:title, :author, :description, :url)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/sessions.rb
class SessionsController < ApplicationController

  def create
      user = User.find_by_email(params[:email])
      # If the user exists AND the password entered is correct.
      if user && user.authenticate(params[:password])
        # Save the user id inside the browser cookie. This is how we keep the user
        # logged in when they navigate around our website.
        session[:user_id] = user.id
        redirect_to '/'
      else
      # If user's login doesn't work, send them back to the login form.
        redirect_to '/login'
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to '/login'
    end

    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      user = User.find_by_username(params[:username])
      # If the user exists AND the password entered is correct.
      if user && user.authenticate(params[:password])
        # Save the user id inside the browser cookie. This is how we keep the user
        # logged in when they navigate around our website.
        session[:user_id] = user.id
        redirect_to '/'
      else
      # If user's login doesn't work, send them back to the login form.
        redirect_to '/login'
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to '/'
    end

    end

app/controllers/users.rb
class UsersController < ApplicationController

       def new
       end

       def create
         user = User.new(user_params)
     if user.save
       session[:user_id] = user.id
       redirect_to root
     else
       redirect_to '/signup'
     end
       end

   end

app/controllers/users_controller.rb
class UsersController < ApplicationController

       def new
         @new_user = User.all
       end

       def create
         user = User.new(user_params)
     if user.save
       session[:user_id] = user.id
       redirect_to '/'
     else
       redirect_to '/signup'
     end
    end
    private

      def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited
        this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :Title
    %br/
    = f.text_field :title
  %p
    = f.label :Author
    %br/
    = f.text_field :author
  %p
    = f.label :Description
    %br/
    = f.text_area :description
  %p
    = f.label :url, "URL"
    %br/
    = f.text_field :url
  %p
    = f.submit

app/views/books/edit.html.haml
%h1 Edit
= render 'form'
= link_to 'back', books_path

app/views/books/index.html.haml
%h1 Freeshelf Book Listing
= link_to 'Add a new book to the freeshelf!', new_book_path, :class => "toplink"
%br
%table.table
  %tr.headrow
    %th.tabhead Title
    %th.tabhead Author
    %th.tabhead Description
    %th.tabhead URL

  - @books.each do |book|
    %tr
      %td= book.title
      %td= book.author
      %td= book.description
      %td= book.url
      %td= link_to 'Show this book', book_path(book)
      - if book.user == current_user
        %td= link_to 'Edit this book', edit_book_path(book)
        %td= link_to 'Delete this book', delete_path(book)

- if current_user
  Signed in as #{current_user.username} | #{link_to "Logout", '/logout'}
- else
  = link_to 'Login', '/login'
  | #{link_to 'Signup', '/signup'}
= yield

app/views/books/new.html.haml
%h1 New Book
= render 'form'
= link_to 'back', books_path

app/views/books/show.html.haml
%p title:
= @book.title
%p author:
= @book.author
%p description:
= @book.description
%p Url:
= @book.url
= link_to 'back', books_path

app/views/users/new.html.haml
%h1 Signup!
= form_for :user, url: '/users' do |f|
  username: #{f.text_field :username}
  Password: #{f.password_field :password}
  Password Confirmation: #{f.password_field :password_confirmation}
  \#{f.submit "Submit"}